# Generated by Django 5.2.8 on 2025-11-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authur',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(default=0),
        ),
    ]
